# Site wide configuration

title: Lei M. Zhang
locale: en_US
## To build the website locally, comment out the previous line and run
## in terminal: 'bundle ex jekyll serve'. The website will be hosted at
## 'localhost:4000'.


# Jekyll configuration

permalink:   /:categories/:year/:month/:day/:title/
markdown:    kramdown
highlighter: rouge
#paginate: 10
#paginate_path: "_site/index/blog/page:num/"
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Lei M. Zhang
  avatar: lei_profile.jpg
  bio: "Senior Research Scientist at Google Deepmind"
  email: leiz86@gmail.com
  twitter: l32zhang
  google_scholar: https://scholar.google.com/citations?user=-kdBDxYAAAAJ&hl=en
  google:
  bing-verify:
  github: leiz86
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: lei-m-zhang  #https://www.linkedin.com/in/lei-m-zhang/
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
